//UMA VEZ QUE O MIGRATIONS NÃO MAPEIA PARA SER DELETE CASCADE NAS 
//CLASSES ASSOCIATIVAS ESSE SCRIPT DEVE SER RODADO

ALTER TABLE dbo."BULAPOSOLOGIA_BPO"
DROP CONSTRAINT "FK_dbo.BULAPOSOLOGIA_BPO_dbo.BULAFACIL_BFA_BPO_RFBFA",
ADD CONSTRAINT "FK_dbo.BULAPOSOLOGIA_BPO_dbo.BULAFACIL_BFA_BPO_RFBFA" FOREIGN KEY ("BPO_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE 
      ON DELETE CASCADE;
      
ALTER TABLE dbo."BULAINDICACAO_BIN"
DROP CONSTRAINT "FK_dbo.BULAINDICACAO_BIN_dbo.BULAFACIL_BFA_BIN_RFBFA",
ADD  CONSTRAINT "FK_dbo.BULAINDICACAO_BIN_dbo.BULAFACIL_BFA_BIN_RFBFA" FOREIGN KEY ("BIN_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE
      ON DELETE CASCADE;

ALTER TABLE dbo."BULACONTRAINDICACAO_BCI"
DROP CONSTRAINT "FK_dbo.BULACONTRAINDICACAO_BCI_dbo.BULAFACIL_BFA_BCI_RFBFA",
ADD CONSTRAINT "FK_dbo.BULACONTRAINDICACAO_BCI_dbo.BULAFACIL_BFA_BCI_RFBFA" FOREIGN KEY ("BCI_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE
      ON DELETE CASCADE;