//UMA VEZ QUE O MIGRATIONS NÃO MAPEIA PARA SER DELETE CASCADE NAS 
//CLASSES ASSOCIATIVAS ESSE SCRIPT DEVE SER RODADO

ALTER TABLE dbo."BULAPOSOLOGIA_BPO"
DROP CONSTRAINT "FK_dbo.BULAPOSOLOGIA_BPO_dbo.BULAFACIL_BFA_BPO_RFBFA",
ADD CONSTRAINT "FK_dbo.BULAPOSOLOGIA_BPO_dbo.BULAFACIL_BFA_BPO_RFBFA" FOREIGN KEY ("BPO_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE 
      ON DELETE CASCADE;
      
ALTER TABLE dbo."BULAINDICACAO_BIN"
DROP CONSTRAINT "FK_dbo.BULAINDICACAO_BIN_dbo.BULAFACIL_BFA_BIN_RFBFA",
ADD  CONSTRAINT "FK_dbo.BULAINDICACAO_BIN_dbo.BULAFACIL_BFA_BIN_RFBFA" FOREIGN KEY ("BIN_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE
      ON DELETE CASCADE;

ALTER TABLE dbo."BULACONTRAINDICACAO_BCI"
DROP CONSTRAINT "FK_dbo.BULACONTRAINDICACAO_BCI_dbo.BULAFACIL_BFA_BCI_RFBFA",
ADD CONSTRAINT "FK_dbo.BULACONTRAINDICACAO_BCI_dbo.BULAFACIL_BFA_BCI_RFBFA" FOREIGN KEY ("BCI_RFBFA")
      REFERENCES dbo."BULAFACIL_BFA" ("BFA_IDBULAFACIL") MATCH SIMPLE
      ON UPDATE CASCADE
      ON DELETE CASCADE;

  ALTER TABLE dbo."FARMACIA_FAR"
  DROP CONSTRAINT "FK_dbo.FARMACIA_FAR_dbo.USUARIO_USU_FAR_USUARIO_USU_FK",
  ADD CONSTRAINT "FK_dbo.FARMACIA_FAR_dbo.USUARIO_USU_FAR_USUARIO_USU_FK" FOREIGN KEY ("FAR_USUARIO_USU_FK")
      REFERENCES dbo."USUARIO_USU" ("USU_IDUSUARIO") MATCH SIMPLE
      ON UPDATE CASCADE 
      ON DELETE CASCADE;


  ALTER TABLE dbo."ENDERECO_END"
  DROP CONSTRAINT "FK_dbo.ENDERECO_END_dbo.FARMACIA_FAR_FAR_ENDERECOFARMACIA_FK",
  ADD CONSTRAINT "FK_dbo.ENDERECO_END_dbo.FARMACIA_FAR_FAR_ENDERECOFARMACIA_FK" FOREIGN KEY ("FAR_ENDERECOFARMACIA_FK")
      REFERENCES dbo."FARMACIA_FAR" ("FAR_USUARIO_USU_FK") MATCH SIMPLE
      ON UPDATE CASCADE 
      ON DELETE CASCADE;