CREATE SCHEMA IF NOT EXISTS "dbo"
;

CREATE TABLE "dbo"."ENDERECO_END"("END_IDENDERECO" serial4 NOT NULL,"END_RUA" varchar(150) NOT NULL,"END_PLUSCODE" varchar(100),"END_CIDADE" varchar(150) NOT NULL,"END_CEP" varchar(15) NOT NULL,"END_UF" varchar(2) NOT NULL,"END_LATITUDE" numeric(18,10) NOT NULL,"END_LONGITUDE" numeric(18,10) NOT NULL,"Pluscode" text,"FAR_ENDERECOFARMACIA_FK" int4 NOT NULL,CONSTRAINT "PK_dbo.ENDERECO_END" PRIMARY KEY ("END_IDENDERECO"))
;

CREATE TABLE "dbo"."FARMACIA_FAR"("FAR_IDFARMACIA" serial4 NOT NULL,"FAR_CNPJ" varchar(50) NOT NULL,"FAR_RAZAOSOCIAL" varchar(100) NOT NULL,"FAR_TELEFONE" varchar(20) NOT NULL,"FAR_EMAIL" varchar(80) NOT NULL,"FAR_SITE" varchar(80) NOT NULL,CONSTRAINT "PK_dbo.FARMACIA_FAR" PRIMARY KEY ("FAR_IDFARMACIA"))
;

CREATE TABLE "dbo"."MEDICAMENTOFARMACIA_MFA"("MFA_IDMEDICAMENTOFARMACIA" serial4 NOT NULL,"MFA_APRESENTACAO" varchar(150) NOT NULL,"MFA_CONCENTRACAO" varchar(150),"MFA_VLPRECO" numeric(18,2) NOT NULL,"MFA_DTINICIO" timestamp NOT NULL,"MFA_DTFIM" timestamp,"MFA_RFFAR" int4 NOT NULL,"MFA_RFMED" int4 NOT NULL,CONSTRAINT "PK_dbo.MEDICAMENTOFARMACIA_MFA" PRIMARY KEY ("MFA_IDMEDICAMENTOFARMACIA"))
;

CREATE TABLE "dbo"."MEDICAMENTO_MED"("MED_IDMEDICAMENTO" serial4 NOT NULL,"MED_NOME" varchar(150) NOT NULL,"MED_TIPO" varchar(150) NOT NULL,"MED_LABORATORIO" varchar(150),CONSTRAINT "PK_dbo.MEDICAMENTO_MED" PRIMARY KEY ("MED_IDMEDICAMENTO"))
;

CREATE TABLE "dbo"."USUARIO_USU"("USU_IDUSUARIO" serial4 NOT NULL,"USU_NOME" varchar(150) NOT NULL,"USU_EMAIL" varchar(150) NOT NULL,"USU_SENHA" text NOT NULL,CONSTRAINT "PK_dbo.USUARIO_USU" PRIMARY KEY ("USU_IDUSUARIO"))
;

CREATE INDEX "ENDERECO_END_IX_FAR_ENDERECOFARMACIA_FK" ON "dbo"."ENDERECO_END" ("FAR_ENDERECOFARMACIA_FK")
;

CREATE INDEX "MEDICAMENTOFARMACIA_MFA_IX_MFA_RFFAR" ON "dbo"."MEDICAMENTOFARMACIA_MFA" ("MFA_RFFAR")
;

CREATE INDEX "MEDICAMENTOFARMACIA_MFA_IX_MFA_RFMED" ON "dbo"."MEDICAMENTOFARMACIA_MFA" ("MFA_RFMED")
;

CREATE UNIQUE INDEX "USUARIO_USU_IDX_USU_EMAIL" ON "dbo"."USUARIO_USU" ("USU_EMAIL")
;

ALTER TABLE "dbo"."ENDERECO_END" ADD CONSTRAINT "FK_dbo.ENDERECO_END_dbo.FARMACIA_FAR_FAR_ENDERECOFARMACIA_FK" FOREIGN KEY ("FAR_ENDERECOFARMACIA_FK") REFERENCES "dbo"."FARMACIA_FAR" ("FAR_IDFARMACIA")
;

ALTER TABLE "dbo"."MEDICAMENTOFARMACIA_MFA" ADD CONSTRAINT "FK_dbo.MEDICAMENTOFARMACIA_MFA_dbo.FARMACIA_FAR_MFA_RFFAR" FOREIGN KEY ("MFA_RFFAR") REFERENCES "dbo"."FARMACIA_FAR" ("FAR_IDFARMACIA") ON DELETE CASCADE
;

ALTER TABLE "dbo"."MEDICAMENTOFARMACIA_MFA" ADD CONSTRAINT "FK_dbo.MEDICAMENTOFARMACIA_MFA_dbo.MEDICAMENTO_MED_MFA_RFMED" FOREIGN KEY ("MFA_RFMED") REFERENCES "dbo"."MEDICAMENTO_MED" ("MED_IDMEDICAMENTO") ON DELETE CASCADE
;

CREATE TABLE "dbo"."__MigrationHistory"("MigrationId" varchar(150) NOT NULL,"ContextKey" varchar(300) NOT NULL,"Model" bytea NOT NULL,"ProductVersion" varchar(32) NOT NULL,CONSTRAINT "PK_dbo.__MigrationHistory" PRIMARY KEY ("MigrationId","ContextKey"))
;

INSERT INTO "dbo"."__MigrationHistory"("MigrationId","ContextKey","Model","ProductVersion") VALUES (E'201912050203363_AutomaticMigration',E'APIBulaFacil.Infra.Data.Migrations.Configuration',decode('H4sIAAAAAAAEAN1cWW/kuBF+D5D/IPRj4O22PQkwMexdaPrYaLcv9DFY5MWg1ey2El2rw7Cz2F+Wh/yk/IUUdYuk2KRa7R4HAxhjifyqiqqLxaL/++//3P/w6tjaCw5Cy3Mfejf9656GXdPbWe7hoRdH++8+9374/o9/uB/vnFftaz7uExkHM93wofccRf7dYBCaz9hBYd+xzMALvX3UNz1ngHbe4Pb6+q+Dm5sBBogeYGna/Sp2I8vByS/w69BzTexHMbJn3g7bYfYc3qwTVG2OHBz6yMQPPX1pfIltNEGmZfcNdx+g/ghFqA8YEX6NeppuWwjYWmN739OQ63oRioDpu22I11HguYe1Dw+QvXnzMYzbIzvEmTB35XBZua5viVyDcmIOZcZh5DmKgDefsoUa0NNbLXevWEhYyjEsefRGpE6W86E3dnc4wKbX02hid0M7IAOp1R7BGMvtJ0AWDvs5wJXGGXZVaAsoFfl3pQ1jO4oD/ODiOAqQfaUt4yfbMn/Gbxvvn9h9cGPbrrIMTMO72gN4tAw8HwfR2wrvM0GMXSnKoD5/QAMU0zlzU5ENN/p029PmwAx6snGhIZXlWUdegH/ELg5QhHdLFEU4cAkWTtaY4YKiuYpRTgw0Eiytp83Q6xS7h+gZbPAvYFsT6xXv8icZA1vXAsOESVEQYw6DYqJDz/Ft7ACHnoj4tRzxI7SsHdrhC8iIfSHRc9Dc7gUkb89BcQpKGMXl+o6waTnI7mlLUGMrc+Sfe9raRATz5lqdAnjJM5NY2nFI1kCwePDfNro4Ry/WIbFTiuQEBQ44KLC9FbaTAeGz5aeRop+/fCzdwSTwnJVnV2YWLx83KDhgCDYbr2nE2osDk+LuflA6YaFrLllt6ZpzgMu75lIUdddczn0v1zx0/X8IVPI8bmuF/oW8tQeC2h24ZkXiG2zjveeKDPH2LITHoIoieT+fheraikSidkS00QeV3uV0H5R7mGYflHspWe5meGeZKMkRwhwt5LJaGVmQLa215Fo0jnGiwsEn+VMOcmvXysG6vJflCqjucLkw7+V7dT/AIQxFJhKmqOfKj2EP6sJn6Yb6keynuuE4klzxFl2MbgArVgkPH2MDm21lmInlsBhHKEuH7GM4FU1UhGqX/3Xi0GiPLOX9WjhnaQlqc8RCVJ5JyVEdzxOljW/uwid/U774RB/8fr537jkX2K9vLP8Cnn6KnjxYJS+wzuDoz5RbtTRkmQyLZ/itDHkbxihZ05ZGnM2/vAEXgqgbbzH1/9twj+3dzkR2jd1nUelUtmIkJNuk73oYki06+WhUQlHu1+rcw2Pt6OYtlaW6/QORQLUtH5QZ2IDFZJZFBFyYfAlcbifrwNf9/g0te0VKsfDChKmJXbnsqeScux+pC/EnwerI7T5lvgDtNhbuCNs4wppupoc7QxSaSc2b9hnATf0JeBr4Gi45goI9Rwi+y3Ij1i1Zrmn5yFaQhMJQrMcRXguq9JsR9rFLPJLCdzydnYIqtaTHVvBELa7GWhXN4mbQZ9VlbqjnUvwYGs2RR06LBCn3yXrN+aydMNW5dqdhi5yDwwwcZHyQw/HibJzJzLYhzpKzMAuOtP4RzDWOmPplGSSZKMPocB2j1H4Go7F2RWNwjYmBk6mKCZDFiEeRilyQQWlKMCsfll2uSlW4Mq6xdEzrm0wyUkhQ/UiM5spkHxWk5rP5urgSSyEu0rCrIp+jqGcpFQkl1Ew9LZH4Fh2tYE2n5RaxMUS2CpIdLyUvKvJJKCxoviso3GvZozRIm5TyZqZBQzfT/Qz5PuxYKt1N2RNtnbY2Db9bq7f5OCnGwAw53T4FtwUl2G2iA6bekur3Dk+sIIxIuHhCZE803DnMsGowaXB+OSUqXrCfMPeJ+QTy/+wgQNzi1W8CLVd0AkKSL5zIi3nOiJmaNJshGwWCBqGhZ8eOm0k2Hz0aI/g5Xo2HC1ZJmxGT9h8aarXVVTBq3Tw01nK6XQ8Xo7ESYNayQ2MNjZGuiESacBiY8VIFgzTV0BDbiQpC2SRD40z1jbHZqslUaYhh4BbzH5Xxyu6XKlz5lEW6H1CqzeSTjEUxaXvdQqXsVxAt29tvE6iE/TZPbbbfMpBUF3uir8B+4edMHxpqtpf0iNBYw/nyJyUvUG36oMFW+t/1xXoBjE1VMMteDhpwM56OJ4u5kpJmRT4aajzTDSWu0pYLGmZtbLjcXEjReYlHlzovgS+h/lIozZbAza6qH2Y20cEoZuORMdRn4/lm0cY+6uf4NLy+XI3XAK0PdaWoWT+fp1GHi/kQQFeqqEs2sBO4r9OlalTPD91pqNHGmBtDQwkrOXlngSbGTImjBs9HwFYT+LJqYLW8mcUDpfk2zflcZnya+bY0W2rlx6O6uap80fTkiIabL2ZKQSI9wqVRNsZSiZfakSwNNtW/LFb6ZrHiG9GFNCyv4XSpXQ2YEprVOLNZq4oiVHW9t+staBT81BtWW16bCJSqNnFSDgKjnnKkB4U0DsSdv3FD2bl1qF5W4KfYlfqeeipdmSy75SVVlIYOKaYyyC6Ycq6d75TzjOJx8jOvKl5hqg2/jacGne7tm9mkK0isNjCFJHpIoYtFQYkqHN1nRZzjd+WYqk46hHQaei/WjlR05v4h/NUun8yQa+1xGKU9FL2b6z653FG7U/ft3G8bhOHO5pS95C65GfDq9aH3m/Z7mzYRsY4c7xWh56fHA5Yb/TkzYVFPiGq7Rl5gSom8oMB8RgHbsdECtqw1CbCva9gyDbLV0lP3TCfVKBFsK1RSoGoGVW+CrRerUmQ3dnBgmR1exKJqWOciQ9/3Ss8j1ZSiMYxUbafZzAnInWb88tiAc6UtAnAWd9o1eIR2PUKM+xHcNjjN/YjLV8fdDz3/nO6nLI81m0cLS2YKZdIeSBq+LJsJDLsddJbTNuN+boeb1tVOgO34Us1pai5dkDqu8QKocyo/W/PqNp6x1S9pfBmfW6uGSQUH9UBXL5Nl8cGCLDZCjt8SLamVCaBkZc8KZYoRppipEFOa6CeFtVb0YeY5Ypr4wsaJ9n6soiVh5yzEWe27KJp1bNdFGa173FpF7QR30cHVgNPURViuOq4q1PRzqklZDev2c1bKYxTwUTcx+uWxmH2lGeHWtX6N4cUGvjPxFh1wlhXc+Cn/O/fen9xrT/+hGGFvPdvK26pLVnBWqLon0FQaYQUtNny6kuW9C7V0H72YoKgktFwnNE8Le9lObyD/UFond0jO3yU0nGh+lFsEF2nc/xZ1T3zC2iJjfEcN5J6Bv1unP9vD2XCQqdLLn54YPPR2T0RF08Cd+3ri9Lvp9udRKSMJa9dd3gfg0eZUCcieqsvLA0fIPnJ0qc0NAx6ZLOEl2d+FryCoXzmglfaDXjFovwACTZftoP9A9wZkO/ffcYkUbgKwB7Xg9Ct/+hTCT2gdSgjyh1BdbNbcfTHGcPdeHngojvIhzJ8ciNAOYoEeRNYemRG8NnEYJremvyI7JubkPOGd4S7iyI8jEBk7T3btzjmJXiL6yXWHOs/3Cz/5iwZdiABsWiACXrhfYsveFXxPOHvHBggSFrONPPmWEdnQH94KpHnSLysDlC1fEc032PFtAAsX7hq94Da8bUM8xQdkvuXH780gxz9EfdnvRxY6BMgJM4xyPvwKOrxzXr//H4gOd1gBWAAA', 'base64'),E'6.2.0-61023')
